 document.getElementById('table').innerHTML=`<table>
        <tr>
        <td id="td">Name</td>
        <td>Age</td>
        <td>Address</td>
        <td>DOB</td>
        </tr>
        <tr>
        <td>John</td>
        <td>14</td>
        <td>Hassan</td>
        <td>20-06-1998</td>
        </tr>
        <tr>
        <td>Dinga</td>
        <td>20</td>
        <td>Mysore</td>
        <td>28-02-2000</td>
        </tr>
        <tr>
        <td>Sundari</td>
        <td>22</td>
        <td>Bangalore</td>
        <td>27-05-1997</td>
        </tr>
        </table>`;

    document.getElementById('list').innerHTML=`<ol>
    <li>Hassan</li>
    <li>Belur</li>
    <li>Bangalore</li>
    <li>Mysore</li>
    </ol>
    <ul>
    <li>Apple</li>
    <li>Mango</li>
    <li>Orange</li>
    <li>Grapes</li>
    <ul>`