let c=document.createElement('Form');
let d=document.createElement('label');
d.textContent='Name';
c.appendChild(d);
let nb=document.createElement('br');
c.appendChild(nb);
let e=document.createElement('input');
e.setAttribute("type","text");
c.appendChild(e);

let f=document.createElement('label');
let br=document.createElement('br');
c.appendChild(br);
let br1=document.createElement('br');
c.appendChild(br1);
f.textContent='Age';
c.appendChild(f);
let nb1=document.createElement('br');
c.appendChild(nb1);
let g=document.createElement('input');
g.setAttribute("type","number");
c.appendChild(g);

let h=document.createElement('label');
let br2=document.createElement('br');
c.appendChild(br2);
let br3=document.createElement('br');
c.appendChild(br3);
h.textContent='Address';
c.appendChild(h);
let nb2=document.createElement('br');
c.appendChild(nb2);
let i=document.createElement('input');
i.setAttribute("type","text");
c.appendChild(i);

let j=document.createElement('label');
let br4=document.createElement('br');
c.appendChild(br4);
let br5=document.createElement('br');
c.appendChild(br5);
j.textContent='DOB';
c.appendChild(j);
let nb3=document.createElement('br');
c.appendChild(nb3);
let k=document.createElement('input');
k.setAttribute("type","date");
c.appendChild(k);

let l=document.createElement('label');
let br6=document.createElement('br');
c.appendChild(br6);
let br7=document.createElement('br');
c.appendChild(br7);
l.textContent='Email';
c.appendChild(l);
let nb4=document.createElement('br');
c.appendChild(nb4);
let m=document.createElement('input');
m.setAttribute("type","email");
c.appendChild(m);

let n=document.createElement('label');
let br8=document.createElement('br');
c.appendChild(br8);
let br9=document.createElement('br');
c.appendChild(br9);
n.textContent='Gender';
c.appendChild(n);
let nb5=document.createElement('br');
c.appendChild(nb5);
let nb6=document.createElement('br');
c.appendChild(nb6);
let o=document.createElement('input');
o.setAttribute("type","radio");
c.appendChild(o);
let p=document.createElement('label');
p.textContent="Male";
c.appendChild(p);
let q=document.createElement('input');
q.setAttribute("type","radio");
c.appendChild(q);
let r=document.createElement('label');
r.textContent="Female";
c.appendChild(r);
let s=document.createElement('input');
s.setAttribute("type","radio");
c.appendChild(s);
let t=document.createElement('label');
t.textContent="Other";
c.appendChild(t);
document.body.appendChild(c);